language: node_js
node_js: "node"
before_script:
  - npm install -g firebase-tools
script: npm run build
after_success:
  - sed -i 's/FIREBASE_NAME/'$FIREBASE_NAME'/g' .firebaserc
  - firebase deploy --token $FIREBASE_TOKEN
branches:
  only: master
cache:
  directories:
  - $HOME/.npm
